### ISSUE TITLE
Problem in plotSC function: overlap of case names and first data points at the top left

### ISSUE THREAD

**Issue by g-in-o** [jazznbass/scan_develop#3]
Hi Jürgen,

I have the problem that I want to plot a SCDA list with a total of three different features of one case with the plotSC function, but the case.names overlap at the top left with the first data points. This is unfortunately the case with all given styles and I haven't found out yet which function in the sytle.plotSC command I can use to put the case.names to the bottom of the graph.

I attach a screenshot of the issue:

![scan_plot](https://user-images.githubusercontent.com/78165709/106170973-53433e00-6191-11eb-83ec-f88d50e0eadc.JPG)

I would like to change the position of the case.names to the down left. I could of course drop the output of the names via case.names"", but for designing a figure in a paper I would then have to laboriously reintegrate the names for each graph. That would be comparatively laborious and the image quality would suffer. I would prefer to change the position of the case.names to the down left. Maybe there is a solution in scan.

Many thanks and best regards

Gino

**Comment by researchtool** [comment]
@jazznbass yup. for decreasing DVs mtext side = 1 or maybe even an additional argument for "upper left", "lower left", "upper right", "lower right" and maybe outside the plot area (side =4)?

@g-in-o if you're in a hurry, here's a quick workaround:
`
##install.packages("scan", repos="http://R-Forge.R-project.org")
##library(scan)

test <- exampleAB_decreasing[1]
plotSC(test, case.names = "")
+mtext("BEHAVIOR 1", side = 1, line = -1, adj = 0)
`

![example](https://user-images.githubusercontent.com/5195357/106198715-b09cb680-61b4-11eb-9ab1-3ba49370bea6.png)

**Comment by jazznbass** [comment]
Unfortunately, this will not work for multiple single-case plots.
But it is a good approach foe a single chart!

**Comment by g-in-o** [comment]
Hi @jazznbass and @researchtool ,

thanks a bunch for the quick replies.
@researchtool I like the approach you have suggested, but to figure a multiple single-case plot, it would not be very comfortable.
@jazznbass Thank you for adressing the problem. I am using version 0.40.

**Comment by jazznbass** [comment]
Hi Gino,
the current scan-develop package (0.50.11 or above) solves your problem.
styles now have a new list argument `names` which is a list with arguments for formatting the case.names depiction in the `plot.scdf()` function.
Simple example to put the text to the lower left side:

new_style <- style_plot()  
new_style$names$side = 1  
plot(exampleAB_decreasing, style = new_style)  

more complex example:

new_style <- style_plot()  
new_style$names$side <- 3  
new_style$names$line <- -1.7  
new_style$names$col <- "darkred"  
new_style$names$cex <- 1.5  
new_style$names$at <- 20  
new_style$names$adj <- 1  
new_style$names$font <- 3  
plot(exampleAB_decreasing, style = new_style)  

I hope this helps.

P.S.: To install the github dev Version of scan:
devtools::install_github("jazznbass/scan_develop")

P.P.S: Don't forget to close this issue when everything works for you :-)

**Comment by g-in-o** [comment]
Hi Jürgen,

thanks a bunch for the fast solution. I have installed the developmental version, and with the aformentioned examples, graphes were plotted as intended:

![Rplot](https://user-images.githubusercontent.com/78165709/107549665-6530d200-6bd0-11eb-9737-dbf1640638da.jpeg)
